[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
auto_detect_solc = false

# Test configuration
[profile.default.fuzz]
runs = 256

# RPC endpoints for different networks
[rpc_endpoints]
zetachain_mainnet = "https://zetachain-mainnet.g.alchemy.com/v2/YOUR_KEY"
local = "http://localhost:8545"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
